#! /bin/bash

#! /bin/bash

case `hostname | head -c 3` in 
    fen) 
	echo fermi
	module load profile/advanced
	module load bgq-xl
	# module load neuron
	/gpfs/scratch/userexternal/ssolinas/neuron/nrnmpignu_xl_stdpy/powerpc64/bin/nrnivmodl  . ../mossy/ ../synapse/ ../gapj/ 2>&1 | tee nrncompile.log
	#/gpfs/scratch/userexternal/ssolinas/neuron/nrnmpignu_xl/powerpc64/bin/nrnivmodl  templates/granule/ templates/golgi/ templates/mossy/ templates/gapj/ templates/synapse/ templates/mli 2>&1 | tee nrncompile.log
        # /fermi/home/userexternal/ssolinas/local/nrn7.3_xl_p2013/powerpc64/bin/nrnivmodl  templates/granule/ templates/golgi/ templates/mossy/ templates/gapj/ templates/synapse/ templates/mli 2>&1 | tee nrncompile.log
        # module unload bgq-xl

	module unload profile/advanced
	module unload bgq-xl
        # module unload neuron
	;;
    bla)
	echo cerfoglio
	nrnivmodl  . ../mossy/ ../synapse/ ../gapj/ 2>&1 | tee nrncompile.log
	;;
    the)
	echo cerfoglio
	/usr/local/neuron/nrn-7.3/x86_64/bin/nrnivmodl  . ../mossy/ ../synapse/ ../gapj/ 2>&1 | tee nrncompile.log
	;;

    ott)
	echo otto
	nrnivmodl . ../mossy_old/ ../mossy/ ../synapse/ 2>&1 | tee nrncompile.log
	;;
esac

