#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/neuron/nrn75/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/neuron/nrn75/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/neuron/projects/rete/control_sims/weasel/templates/mossy/x86_64/.libs/libnrnmech.so" "$@"
